### ISSUE TITLE
LL(1) validator for syntactic_spec

### ISSUE THREAD

**Issue by AksharP5** [ourPLCC/plcc-reorg#18]
The grammar must be in LL(1).

Rough Outline of the process: 
- [x] Grammar
    - [x] Grammar Tests
- [x] LL1Wrapper
    - [x] LL1Wrapper Tests
- [x] SpecGrammar
    - [x] SpecGrammar Tests
- [ ] LL1Checker
    - [ ] LL1Checker Tests
- [x] LL1Validator
    - [ ] LL1Validator Tests

**Comment by StoneyJackson** [comment]
In our meeting this morning, Tim reminded me that repeating rules must first be replaced with an equivalent set of non-repeating rules. Here is the area of the original code that does this. https://github.com/ourPLCC/plcc/blob/b5a66eccedebe6a13e2a9459629b6bc281e7bbe0/src/plcc/__main__.py#L450 .

You can still proceed by just assuming all specs only have non-repeating rules. Then we can write a something that will translate a spec within repeating rules into one that does not have repeating rules.

**Comment by StoneyJackson** [comment]
The idea is, build the table for a predictive parser. If that table is invalid, then the grammar is not in LL(1).

This page has a good description of this: https://pages.cs.wisc.edu/~hasti/cs536/readings/Topdown.html#follow

Specifically, we need to:

1. Build the FIRST set.
2. Build the FOLLOW set (using FIRST).
3. Build the Table (using FIRST and FOLLOW).
4. Check if Table has any duplicate entries. If it does, the grammar is not in LL(1).

Now the existing checkLL1 (https://github.com/ourPLCC/plcc/blob/b5a66eccedebe6a13e2a9459629b6bc281e7bbe0/src/plcc/__main__.py#L510) does this. But it also populates `cases` which is not essential to checking LL1. It's related to code generation. Also, some of the check comes during code generation (https://github.com/ourPLCC/plcc/blob/b5a66eccedebe6a13e2a9459629b6bc281e7bbe0/src/plcc/__main__.py#L664 and https://github.com/ourPLCC/plcc/blob/b5a66eccedebe6a13e2a9459629b6bc281e7bbe0/src/plcc/__main__.py#L799). Ideally all of those checks should happen in the new LL1 validator.

To wrap my head around this, I have been working on a new implementation based  on https://pages.cs.wisc.edu/~hasti/cs536/readings/Topdown.html#follow .  Both the existing checkLL1 and what I have tinkered with treat terminals and non-terminals in the spec as strings. We need to make sure that when a non-terminal appears on the LHS or the RHS they will be considered the same as long as their name within angles is the same. To make this work, I'm thinking we may need to create a wrapper class. Each instance would contain one of the instances of the objects produced by the syntactic parser. The wrapper would implement __hash__ and __equals__ so that non-terminals and terminals would be equal if they have the same name (within angles). Basically, the wrapper class needs to work correctly with Python's set and ==.

There will need to be an adapter method/class/something that converts the spec produced by our parser into rules that have the form (nonterminal, (terminals and nonterminals)). That is, a tuple containing the nonterminal and a tuple. The inner tuple containing terminals and nonterminals. This structure would be the input for the new LL1 validator.

With some modifications the existing checkLL1 may be able to use this structure.

There are a couple of unknowns here:
* The algorithm described https://pages.cs.wisc.edu/~hasti/cs536/readings/Topdown.html#follow adds an EOF to FOLLOW in certain cases. EOF is not used in the original checkLL1. Would it help or hurt to use EOF?
* Does the algorithm described https://pages.cs.wisc.edu/~hasti/cs536/readings/Topdown.html#follow handle the checks that are currently in code generation? And how would we incorporate them into the existing checkLL1? If that's too challenging or impossible, maybe we should rewrite checkLL1.

There may be other issues. But that's what I got for now.

**Comment by AksharP5** [comment]
@StoneyJackson 

I have taken a look at the documentation provided and the suggestions, and I just have a few questions to ensure that I am on the same page as you with this implementation:

### Questions

1. You have mentioned the current checkLL1 using this structure, just to be clear, I was under the impression that we are going to be refactoring the current LL1 validator, my vision was a class-based approach with the 4 steps mentioned above (unless there are more):
```
class LL1Validator:
    def __init__(self, adapted_syntactic_spec):
        self.syntacticSpec = adapted_syntactic_spec
        self.firstSets = {} # dictionaries to hold each set, may change later?
        self.followSets = {}
        self.parsingTable = {}

    def checkLL1(self):
        self._generateFirstSets()
        self._generateFollowSets()
        self._buildParsingTable()
        return self._checkParsingTable()
```
2. The adapter class and the wrapper class seem like a good idea to standardize the format of the input, and it will help make the methods simpler for the checks, my current understanding of each looks something like this:
```
Wrapper Class:
    equals(symbol): 
    hash(symbol):

...

Adapter Class:
    adapt():
        # use wrapper class for each rule's lhs and rhs (can be more than one item), append a tuple (lhs, rhs)
```

Should the equals method check only for the symbol name, or should it also check for the class of the symbol? I am asking this, because I am not sure if it will count a Terminal and Non-Terminal with the same name as equivalent, and if that is even a possibility where the two can have the same name? Checking the __class__ can ensure that this won't happen. If we do end up checking the __class__ then the hash should also take the class as an input along with the name to distinguish Terminals and Non-Terminals.

### Comments Regarding Unknowns

I believe that adding an EOF, can be useful? I am not entirely sure about this, but from my understanding it will only help with using the parsing table to ensure that the it handles the end of input properly, however if the current checkLL1 does not use it and everything works as intended, leaving it out can be fine, but is it best practice to include it? I am basing this off the document provided.

Once again this goes back to my earlier question, are we going to be modifying the current checkLL1? I was under the impression that this is going to be a new thing entirely, please let me know if I am mistaken.

**Comment by AksharP5** [comment]
Regarding my comment about the __eq__ method for the wrapper class, I believe that adding a field for isTerm should resolve the issue with Terminals and Nonterminals, and then the hash function should take both the name and isTerminal as parameters to distinguish the items? Unless there is no need for this, and just using the name is fine

**Comment by StoneyJackson** [comment]
@AksharP5 

## `class LL1Validator`

You got the idea. But let's split the LL1Validator from the LL1Checker. So rename your LL1Validator LL1Checker. The LL1Checker will implement the algorithm using simple structures (strings, dict, list, tuples, set, etc.). Then LL1Validator will be responsible for instantiating an adaptor Grammar, loading it with the stuff from the spec, running the checker, and returning the result/errors.

## `Grammar`

I suggest `LL1Checker` take a `Grammar` object as a parameter instead of a spec. This object will have the interface that LL1Checker needs. LL1Validator will use a specialization of Grammar that adapts the spec structures into whatever is needed for LL1Checker. This will help isolate LL1Checker from the rest of the system and should protect it from change. This is important because this is a complicated algorithm that we need to get right. And we don't want changes to the rest of the system to require someone to check the details of this algorithm to see if the change will break it.

As you build LL1Checker, you will place demands on `Grammar` (e.g., addRule(nonterm, form), getStartSymbol(), isTerminal(sym), isNonterminal(sym), getTerminals(), getNonterminals(), getRules(), etc.). The default implementation of `Grammar` could assume that all symbols are strings. Tests would use the default implementation too and be written in terms of strings. The goal is to keep Grammar simple. Then we'll adapt PLCC data structures to it by inheriting from Grammar and overriding methods that add rules, and hopefully the rest works :)

## `Wrapper Class`

This would also be implemented by the code that implements the adapter Grammar. It should store an instance of one of the spec structures (e.g., LhsNonterminal, CapturingTerminal, RhsNonterminal, Terminal -- these may not be the right names, I'm working from memory). What the wrapper class returns from `__eq__` and `__hash__` should be the "basic name" of the symbol it contains (e.g.,  the base name for `<blah>:blee` is `blah`). And so, a LhsNonterminal that has the same name as a RhsNonterminal are the same symbol for the sake of the grammar. Same for terminals and captured terminals. A terminal will never match a nonterminal because of casing; so you don't have to worry about this.

Also, you probably don't need this while implementing the checker. Just when you get to the validator.

I'll make another comment with a class diagram.

**Comment by StoneyJackson** [comment]
```mermaid
classDiagram

    class LL1Validator {

    }

    class LL1Checker {
        __init__(Grammar)
        check() List[Error]
    }

    class Grammar {
        addRule(nonterminal: Object, form: Iterable[Object])
        isTerminal(Object) bool
        isNonterminal(Object) bool
    }

    Grammar <|-- SpecGrammar

    class SpecGrammar {
        addRule(nonterminal, form) // wraps objects
    }

    LL1Validator ..>"Creates" LL1Checker
    LL1Validator ..>"Creates" SpecGrammar

    class Wrapper {
        specObject
        name
        __init__(name, specObject)
        __eq__(other) bool // compares names
        __hash__() int // hashes name
    }

    LL1Checker ..>"Uses" Grammar
    SpecGrammar ..>"Creates" Wrapper
```

What I couldn't convey in the diagram is that

* LL1Checker and Grammar are in the same module/namespace and depends on Error (whatever the name of that error class is).
* SpecGrammar and Wrapper are in the same module/namespace and depend on Grammar and Spec.
* LL1Validator is dependent on most of the above.

**Comment by AksharP5** [comment]
@StoneyJackson 

This is much easier to understand now, I just want to make sure that I am completely understanding everything, so I will layout what I have gathered so far, and please let me know if there is anything that I have incorrect:

1. When you mention two classes being in the same module/namespace, do you mean the same file, or should each part be its own directory? From what I understand from above, LL1Checker, Grammar, and the ValidationError class should be in the same file, and SpecGrammar and Wrapper should be in their own file, this would mean that LL1Validator is its own file, that imports/depends upon what is needed, correct?

LL1Checker/Grammar/Error File (what should this be named? Assuming this is the correct structure of the file) 
```
class ValidationError:
# distinguished from others by the message
...
class LL1Checker:
# FIRST sets
# FOLLOW sets
# Parsing Table
# Check for duplicates
...
class Grammar:
# init
# addRule
# isTerminal
# isNonterminal
# getStartSymbol
# setStartSymbol
# getTerminals
# getNonterminals
# getRules
# etc
```

A couple questions about the classes within this file:
* I am assuming that all errors in the errorList will be ValidationErrors still? Unless the LL1Checker should use a separate error class?
* Is the Grammar class an abstract class? Also, what is the purpose of keeping this class in the same file as the LL1Checker, and not with the SpecGrammar class? Is it simply for extensibility and to decouple the components? Or is this understanding wrong, and each part should be its own file, and then import as needed? 

SpecGrammar/Wrapper file (again with any name suggestions?)
```
class Wrapper():
...
class SpecGrammar(Grammar): 
```
* Is this correct?: The SpecGrammar is being utilized by the LL1Validator, with the lhs and rhsList as the parameters, they are called nonterminal and form in the diagram above. Specifically, the addRule method will be utilized when looping over the syntactic_spec, to add each rule to the SpecGrammar, which should be in the form ```Wrapper(Wrapper(nonterminal.name, nonterminal), [Wrapper(symbol.name, symbol)])```, where the the rhs is a list or tuple of Wrapper objects for each symbol? This means that everything in the SpecGrammar should be an instance of the Wrapper class, correct?
* Also, assuming that the SpecGrammar overrides each Grammar method, should it be under the impression that each nonterminal is the object itself, not a string representation?
* The __eq__ check in the Wrapper class should only compare the names, however should it ensure that both objects are instances of Wrapper, or be under the assumption that this is the case?

LL1Validator
```
class LL1Validator()
    # loop over syntactic_spec and then convert each rule to SpecGrammar rule, then call upon LL1Checker on the SpecGrammar, returns errorList
```

**Comment by AksharP5** [comment]
Also, one other thing that I encountered when trying to fully understand everything, when looking at the documentation, there is an epsilon in the FIRST set, this represents an empty string, '', and from what I know so far for our BNF section, we do not have an | operator allowed within a rule (unless I am mistaken), it is required to generate a new rule with an alt name that just has '', this is an example I found while looking through some things:
```
<mangle>         **= RANGLE <exp> LPAREN <rands> RPAREN
<ext>:Ext1       ::= EXTENDS <exp>
<ext>:Ext0       ::=
<loc>:ObjLoc     ::= LANGLE <exp> RANGLE
```

I have not yet tested this out, but we will need to verify that the current parser handles this case properly, as '' will need to be added to the FIRST sets for nonterminals in the checker. 

This is just a note that I wanted to make as I encountered it when looking through documentation, however it may well be handled properly already, I just wanted to write it somewhere so I don't forget.

**Comment by StoneyJackson** [comment]
@AksharP5  Sorry, I won't have time to answer all of these questions in writting in the near future. Based on my quick skim, I think you have a good understanding of the problem and roughly how to solve it.

I can easily answer your second message: yes, an empty rule is epsilon. So you'll need to add it or account for it somehow. You might look at the existing checker for clues.
